return {
    EasingStyle = {
        Linear = "Linear",
        Exponential = "Exponential",
        Cubic = "Cubic",
        Quart = "Quart",
        Quint = "Quint",
        Sine = "Sine",
        Bounce = "Bounce",
        Back = "Back",
        Elastic = "Elastic"
    },
    
    EasingDirection = {
        In = "In",
        Out = "Out",
        InOut = "InOut"
    },

    MouseInputs = {
        LeftClick = "LeftClick";
        RightClick = "RightClick";
        MiddleMousePress = "MiddleMousePress";
        ExtraMouse1 = "ExtraMouse1";
        ExtraMouse2 = "ExtraMouse2"
    };

        KeyInputs = {
            a = "a";
            b = "b";
            c = "c";
            d = "d";
            e = "e";
            f = "f";
            g = "g";
            h = "h";
            i = "i";
            j = "j";
            k = "k";
            l = "l";
            m = "m";
            n = "n";
            o = "o";
            p = "p";
            q = "q";
            r = "r";
            s = "s";
            t = "t";
            u = "u";
            v = "v";
            w = "w";
            x = "x";
            y = "y";
            z = "z";
            
            zero = "0";
            one = "1";
            two = "2";
            three = "3";
            four = "4";
            five = "5";
            six = "6";
            seven = "7";
            eight = "8";
            nine = "9";
            
            space = "space";
            exclamation = "!";
            doublequote = "\"";
            hash = "#";
            dollar = "$";
            ampersand = "&";
            singlequote = "'";
            leftparen = "(";
            rightparen = ")";
            asterisk = "*";
            plus = "+";
            comma = ",";
            hyphen = "-";
            period = ".";
            slash = "/";
            colon = ":";
            semicolon = ";";
            lessthan = "<";
            equal = "=";
            greaterthan = ">";
            question = "?";
            at = "@";
            leftbracket = "[";
            backslash = "\\";
            rightbracket = "]";
            caret = "^";
            underscore = "_";
            grave = "`";

            keypad0 = "kp0";
            keypad1 = "kp1";
            keypad2 = "kp2";
            keypad3 = "kp3";
            keypad4 = "kp4";
            keypad5 = "kp5";
            keypad6 = "kp6";
            keypad7 = "kp7";
            keypad8 = "kp8";
            keypad9 = "kp9";
            keypadperiod = "kp.";
            keypadcomma = "kp,";
            keypaddivide = "kp/";
            keypadmultiply = "kp*";
            keypadminus = "kp-";
            keypadplus = "kp+";
            keypadenter = "kpenter";
            keypadequals = "kp=";
            
            up = "up";
            down = "down";
            right = "right";
            left = "left";
            home = "home";
            ["end"] = "end";
            pageup = "pageup";
            pagedown = "pagedown";
            
            insert = "insert";
            backspace = "backspace";
            tab = "tab";
            clear = "clear";
            enter = "return";
            delete = "delete";
            
            f1 = "f1";
            f2 = "f2";
            f3 = "f3";
            f4 = "f4";
            f5 = "f5";
            f6 = "f6";
            f7 = "f7";
            f8 = "f8";
            f9 = "f9";
            f10 = "f10";
            f11 = "f11";
            f12 = "f12";
            f13 = "f13";
            f14 = "f14";
            f15 = "f15";
            f16 = "f16";
            f17 = "f17";
            f18 = "f18";
            
            numlock = "numlock";
            capslock = "capslock";
            scrolllock = "scrolllock";
            rightshift = "rshift";
            leftshift = "lshift";
            rightcontrol = "rctrl";
            leftcontrol = "lctrl";
            rightalt = "ralt";
            leftalt = "lalt";
            rgui = "rgui";
            lgui = "lgui";
            mode = "mode";
            
            www = "www";
            mail = "mail";
            calculator = "calculator";
            computer = "computer";
            appsearch = "appsearch";
            apphome = "apphome";
            appback = "appback";
            appforward = "appforward";
            apprefresh = "apprefresh";
            appbookmarks = "appbookmarks";
            
            pause = "pause";
            escape = "escape";
            help = "help";
            printscreen = "printscreen";
            sysreq = "sysreq";
            menu = "menu";
            application = "application";
            power = "power";
            currencyunit = "currencyunit";
            undo = "undo";
        };

    CursorType = {
        arrow = "arrow";
        ibeam = "ibeam";
        wait = "wait";
        waitarrow = "waitarrow";
        crosshair = "crosshair";
        sizenwse = "sizenwse";
        sizenesw = "sizenesw";
        sizewe = "sizewe";
        sizens = "sizens";
        sizeall = "sizeall";
        no = "no";
        hand = "hand"
    }
}
